#!/usr/bin/env node
/**
 * Post-build: copies a thin plugin loader into the global OpenCode plugins
 * directory so it is auto-discovered on every OpenCode session, regardless
 * of which project the user opens.
 *
 * Target: ~/.config/opencode/plugins/hybrid-runtime.js
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const distPlugin = resolve(
  __dirname,
  "..",
  "dist",
  "src",
  "opencode",
  "plugin.js",
);

// Convert to file:// URL so the import works cross-platform.
const distURL = new URL(`file:///${distPlugin.replace(/\\/g, "/")}`).href;

const globalPluginsDir = resolve(homedir(), ".config", "opencode", "plugins");
mkdirSync(globalPluginsDir, { recursive: true });

const loaderPath = resolve(globalPluginsDir, "hybrid-runtime.js");
const loaderContent = `// Auto-generated by hybrid-framework postbuild – do not edit.
export { HybridRuntimePlugin } from "${distURL}";
export { default } from "${distURL}";
`;

writeFileSync(loaderPath, loaderContent, "utf8");
console.log(`[hybrid-framework] Plugin loader → ${loaderPath}`);
